import { BaanService } from "./baanService.js";
import { BhaaiService } from "./bhaaiService.js";
import { CustomerService } from "./customerService.js";
import { NimtaService } from "./nimtaService.js";
import { PariwarRolesService } from "./pariwarRoleservice.js";
import { PariwarService } from "./pariwarService.js";
import { RelativeService } from "./relativeService.js";
import { BaanModel } from "../models/baanModel.js";
import { BhaaiModel } from "../models/bhaaiModel.js";
import { CustomerModel } from "../models/customerModel.js";
import { NimtaModel } from "../models/nimtaModel.js";
import { PariwarModel } from "../models/pariwarModel.js";
import { RelativeModel } from "../models/relativeModel.js";
import { PariwarRolesModel } from "../models/pariwarRolesModel.js";
import { SecurityService } from "./securityService.js";

export const baanService = new BaanService(BaanModel);
export const bhaaiService = new BhaaiService(BhaaiModel);
export const customerService = new CustomerService(CustomerModel, bhaaiService);
export const nimtaService = new NimtaService(NimtaModel);
export const pariwarRolesService = new PariwarRolesService(PariwarRolesModel, customerService);
export const pariwarService = new PariwarService(PariwarModel, pariwarRolesService);
export const relativeService = new RelativeService(RelativeModel, nimtaService);
export const securityService = new SecurityService();